### ISSUE TITLE
44636A6C is a bad dump of Adventure player

### ISSUE THREAD

**Issue by RetroGameTalk** [tehmugi/patches_release#1]
Hi, as you can see here https://renascene.com/psp/info/umd/59
44636A6C is a bad dump of Adventure player
You need to apply the fix found at DUMPS_FIX_PACK_4_iNTERNAL_PSP-PLAYASiA
And it will become A3CA9117 which is the good dump.
Regards!

**Comment by tehmugi** [comment]
im aware of this.
the iso used for this is a 2048KB underdump that has no impact on the game's functionality, and is a very commonly available dump, which is why i chose to target it.

i'll address this once my copy of the umd stops being stuck in the mail.
